#!/bin/sh

LOADER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LOADER_SCRIPTS_DIR=$LOADER_DIR/.
LOADER_DEST_DIR=$LOADER_DIR/.
LOADER_TARGET_FILE=loader.zip

LOADER_COMPILE_BIN=$QUICK_V3_ROOT/quick/bin/compile_scripts.sh

# 编译游戏脚本文件
rm -f $LOADER_DEST_DIR/$LOADER_TARGET_FILE
$LOADER_COMPILE_BIN -i $LOADER_SCRIPTS_DIR -o $LOADER_DEST_DIR/$LOADER_TARGET_FILE
